name = "MysticetiProofs"
version = "0.1.0"
defaultTargets = ["MysticetiProofs"]

[[lean_lib]]
name = "MysticetiProofs"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.2"
